//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuctionSystem {
    
    
    public partial class ViewProducts {
        
        /// <summary>
        /// ctrlViewProducts1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineAuctionSystem.UserControl.ctrlViewProducts ctrlViewProducts1;
        
        /// <summary>
        /// ctrlViewProducts2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineAuctionSystem.UserControl.ctrlViewProducts ctrlViewProducts2;
        
        /// <summary>
        /// ctrlViewProducts3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineAuctionSystem.UserControl.ctrlViewProducts ctrlViewProducts3;
    }
}
